export const statusFilterOptions = [
  'Testiran',
  'Zaražen',
  'Ne testiran',
  'Preminuo',
];
export const cityFilterOptions = [
  'Aleksinac',
  'Ada',
  'Aleksandrovac',
  'Alibunar',
  'Apatin',
  'Aranđelovac',
  'Arilje',
  'Babušnica',
  'Bajina Bašta',
  'Barajevo',
  'Batočina',
  'Bač',
  'Bačka Palanka',
  'Bačka Topola',
  'Bački Petrovac',
  'Bela Palanka',
  'Bela Crkva',
  'Beočin',
  'Bečej',
  'Blace',
  'Bogatić',
  'Bojnik',
  'Boljevac',
  'Bor',
  'Bosilegrad',
  'Brus',
  'Bujanovac',
  'Varvarin',
  'Velika Plana',
  'Veliko Gradište',
  'Vitina',
  'Vladimirci',
  'Vladičin Han',
  'Vlasotince',
  'Voždovac',
  'Vranjska Banja',
  'Vračar',
  'Vrbas',
  'Vrnjačka Banja',
  'Vršac',
  'Vučitrn',
  'Gadžin Han',
  'Glogovac',
  'Gnjilane',
  'Golubac',
  'Gora sedište Dragaš',
  'Gornji Milanovac',
  'Grocka',
  'Despotovac',
  'Dečani',
  'Dimitrovgrad',
  'Doljevac',
  'Đakovica',
  'Žabalj',
  'Žabari',
  'Žagubica',
  'Žitište',
  'Žitorađa',
  'Zvezdara',
  'Zvečan',
  'Zemun',
  'Zubin Potok',
  'Ivanjica',
  'Inđija',
  'Irig',
  'Istok',
  'Kanjiža',
  'Kačanik',
  'Kikinda',
  'Kladovo',
  'Klina',
  'Knić',
  'Knjaževac',
  'Kovačica',
  'Kovin',
  'Kosjerić',
  'Kostolac',
  'Kosovo Polje',
  'Kosovska Kamenica',
  'Kosovska Mitrovica',
  'Koceljeva',
  'Kragujevac',
  'Krupanj',
  'Kula',
  'Kuršumlija',
  'Kučevo',
  'Lazarevac',
  'Lajkovac',
  'Lapovo',
  'Lebane',
  'Leposavić',
  'Lipljan',
  'Lučani',
  'Ljig',
  'Ljubovija',
  'Majdanpek',
  'Mali Zvornik',
  'Mali Iđoš',
  'Malo Crniće',
  'Medveđa',
  'Mediana',
  'Merošina',
  'Mionica',
  'Mladenovac',
  'Negotin',
  'Niška Banja',
  'Nova Varoš',
  'Nova Crnja',
  'Novi Beograd',
  'Novi Bečej',
  'Novi Kneževac',
  'Novi Sad',
  'Novo Brdo',
  'Obilić',
  'Obrenovac',
  'Opovo',
  'Orahovac',
  'Osečina',
  'Palilula-Beograd',
  'Palilula-Niš',
  'Pantelej',
  'Paraćin',
  'Petrovaradin',
  'Petrovac na Mlavi',
  'Peć',
  'Pećinci',
  'Pirot',
  'Plandište',
  'Podujevo',
  'Požega',
  'Preševo',
  'Priboj',
  'Prizren',
  'Prijepolje',
  'Priština',
  'Prokuplje',
  'Ražanj',
  'Rakovica',
  'Rača',
  'Raška',
  'Rekovac',
  'Ruma',
  'Savski venac',
  'Svilajnac',
  'Svrljig',
  'Sevojno',
  'Senta',
  'Sečanj',
  'Sjenica',
  'Smederevska Palanka',
  'Sokobanja',
  'Sopot',
  'Srbica',
  'Srbobran',
  'Sremski Karlovci',
  'Stara Pazova',
  'Stari grad',
  'Stragari',
  'Suva Reka',
  'Surdulica',
  'Surčin',
  'Temerin',
  'Titel',
  'Topola',
  'Trgovište',
  'Trstenik',
  'Tutin',
  'Ćićevac',
  'Ćuprija',
  'Ub',
  'Uroševac',
  'Crveni krst',
  'Crna Trava',
  'Čajetina',
  'Čoka',
  'Čukarica',
  'Šid',
  'Štimlje',
  'Štrpce',
  'Valjevo',
  'Vranje',
  'Zaječar',
  'Zrenjanin',
  'Jagodina',
  'Kraljevo',
  'Kruševac',
  'Leskovac',
  'Loznica',
  'Novi Pazar',
  'Pančevo',
  'Požarevac',
  'Smederevo',
  'Sombor',
  'Sremska  Mitrovica',
  'Subotica',
  'Užice',
  'Čačak',
  'Šabac',
  'Odžaci',
];

export const listData = [
  {id: '000001', grad: 'Beograd', status: 'Testiran', simptomi: '-'},
  {
    id: '000002',
    grad: 'Kragujevac',
    status: 'Zaražen',
    simptomi: 'Jaki simptomi',
  },
  {id: '000003', grad: 'Subotica', status: 'Nije testiran', simptomi: '-'},
  {id: '000004', grad: 'Vranje', status: 'Zaražen', simptomi: 'Bez simptoma'},
  {id: '000005', grad: 'Valjevo', status: 'Preminuo', simptomi: '-'},
  {id: '000006', grad: 'Vranje', status: 'Zaražen', simptomi: 'Bez simptoma'},
  {id: '000007', grad: 'Vranje', status: 'Zaražen', simptomi: 'Bez simptoma'},
  {id: '000008', grad: 'Vranje', status: 'Zaražen', simptomi: 'Bez simptoma'},
  {id: '000009', grad: 'Vranje', status: 'Zaražen', simptomi: 'Bez simptoma'},
  {id: '000010', grad: 'Vranje', status: 'Zaražen', simptomi: 'Bez simptoma'},
  {id: '000011', grad: 'Vranje', status: 'Zaražen', simptomi: 'Bez simptoma'},
  {id: '000012', grad: 'Vranje', status: 'Zaražen', simptomi: 'Bez simptoma'},
  {id: '000013', grad: 'Vranje', status: 'Zaražen', simptomi: 'Bez simptoma'},
  {id: '000014', grad: 'Vranje', status: 'Zaražen', simptomi: 'Bez simptoma'},
  {id: '000015', grad: 'Vranje', status: 'Zaražen', simptomi: 'Bez simptoma'},
  {id: '000016', grad: 'Vranje', status: 'Zaražen', simptomi: 'Bez simptoma'},
  {id: '000017', grad: 'Vranje', status: 'Zaražen', simptomi: 'Bez simptoma'},
  {id: '000018', grad: 'Vranje', status: 'Zaražen', simptomi: 'Bez simptoma'},
  {id: '000019', grad: 'Vranje', status: 'Zaražen', simptomi: 'Bez simptoma'},
  {id: '000020', grad: 'Vranje', status: 'Zaražen', simptomi: 'Bez simptoma'},
];
